const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const { buildLayoutPlan } = require('./layoutEngine');
const { isLayoutDebugEnabled, drawDebugOverlay } = require('./layoutDebug');
const { SECTION_VARIANTS } = require('./sectionContract');

const BRAND = '#5b3a9e';
const MARGIN = 50;
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_RESERVED = 58;
const PAGE_BOTTOM = PAGE_HEIGHT - FOOTER_RESERVED;
const PAGE_TOP = MARGIN;
const SECTION_GAP = 10;
const MINOR_GAP = 6;
let LAYOUT_MANAGED_RENDER = false;
const COVER_LOGO_PATH = path.resolve(__dirname, '../../../../frontend/src/assets/GSN Solutions 2.png');
const REPORT_TEMPLATE_PATH = path.resolve(__dirname, '../../../../frontend/src/assets/report_template.png');

const HEALTH_FACTORS = [
  {
    key: 'powerFactor',
    label: 'Power Factor',
    description: 'How efficiently the fleet uses electrical power',
  },
  {
    key: 'voltageStability',
    label: 'Voltage Stability',
    description: 'How stable supply voltage stayed during the period',
  },
  {
    key: 'alarmFrequency',
    label: 'Alarm Frequency',
    description: 'How often alarms were triggered across the fleet',
  },
  {
    key: 'meterAvailability',
    label: 'Meter Availability',
    description: 'Share of meters communicating at report generation',
  },
  {
    key: 'offlineDuration',
    label: 'Communication Uptime',
    description: 'How long offline meters stayed disconnected',
  },
];

function healthScoreTone(score) {
  const value = Math.max(0, Math.min(100, Number(score) || 0));
  if (value >= 90) return { label: 'Excellent', color: '#198754', tint: '#d1e7dd' };
  if (value >= 75) return { label: 'Good', color: '#0d6efd', tint: '#cfe2ff' };
  if (value >= 60) return { label: 'Fair', color: '#fd7e14', tint: '#fff3cd' };
  return { label: 'Needs attention', color: '#dc3545', tint: '#f8d7da' };
}

function drawHealthStatusPill(doc, x, y, width, score) {
  const tone = healthScoreTone(score);
  doc.roundedRect(x, y, width, 14, 7).fillColor(tone.tint).fill();
  doc.fontSize(6.5).fillColor(tone.color).font('Helvetica-Bold')
    .text(tone.label, x, y + 3.5, { width, align: 'center' });
  return tone;
}

function drawMiniHealthBar(doc, x, y, width, score, color) {
  const value = Math.max(0, Math.min(100, Number(score) || 0));
  doc.roundedRect(x, y, width, 6, 3).fillColor('#e9ecef').fill();
  if (value > 0) {
    doc.roundedRect(x, y, Math.max(4, (value / 100) * width), 6, 3).fillColor(color).fill();
  }
}

function formatIstDateTime(date) {
  return new Date(date).toLocaleString('en-IN', {
    timeZone: 'Asia/Kolkata',
    dateStyle: 'medium',
    timeStyle: 'short',
  });
}

function formatPeriodRange(from, to) {
  const opts = { timeZone: 'Asia/Kolkata', dateStyle: 'medium' };
  return `${new Date(from).toLocaleDateString('en-IN', opts)} — ${new Date(to).toLocaleDateString('en-IN', opts)}`;
}

function addPageFooter(doc, pageNum, totalPages, generatedAt) {
  const y = PAGE_HEIGHT - 42;
  doc.fontSize(7.5).fillColor('#6c757d');
  doc.text(
    `Generated by Energy Dashboard · ${formatIstDateTime(generatedAt)} · Page ${pageNum} of ${totalPages}`,
    MARGIN,
    y,
    { align: 'center', width: CONTENT_WIDTH }
  );
  doc.text(
    'Prepared By: _______________    Verified By: _______________    Approved By: _______________',
    MARGIN,
    y + 11,
    { align: 'center', width: CONTENT_WIDTH }
  );
}

function sectionTitle(doc, title, y) {
  doc.fillColor(BRAND).fontSize(13).font('Helvetica-Bold').text(title, MARGIN, y);
  doc.moveTo(MARGIN, y + 16).lineTo(PAGE_WIDTH - MARGIN, y + 16).strokeColor(BRAND).lineWidth(0.75).stroke();
  return y + 24;
}

function ensureSpace(y, needed, { majorBreak = false, minOrphanRows = 0 } = {}) {
  const required = needed + minOrphanRows;
  if (LAYOUT_MANAGED_RENDER) {
    if (majorBreak && y > PAGE_TOP + 40) {
      return { y: PAGE_TOP, newPage: true };
    }
    if (y + required > PAGE_BOTTOM) {
      return { y: PAGE_TOP, newPage: true };
    }
    return { y, newPage: false };
  }
  if (majorBreak && y > PAGE_TOP + 40) {
    return { y: PAGE_TOP, newPage: true };
  }
  if (y + required > PAGE_BOTTOM) {
    return { y: PAGE_TOP, newPage: true };
  }
  return { y, newPage: false };
}

function applyPage(doc, state, result) {
  if (LAYOUT_MANAGED_RENDER) {
    if (result.newPage) addReportPage(doc);
    return result.newPage ? PAGE_TOP : result.y;
  }
  if (result.newPage) addReportPage(doc);
  return result.y;
}

function maybeAddPage(doc) {
  if (LAYOUT_MANAGED_RENDER) return false;
  addReportPage(doc);
  return true;
}

function drawPageTemplate(doc) {
  if (!fs.existsSync(REPORT_TEMPLATE_PATH)) return;
  doc.image(REPORT_TEMPLATE_PATH, 0, 0, {
    width: PAGE_WIDTH,
    height: PAGE_HEIGHT,
  });
}

function addReportPage(doc) {
  doc.addPage();
  drawPageTemplate(doc);
}

function renderCoverPage(doc, payload) {
  const { meta } = payload;
  const logoBox = { x: MARGIN, y: 48, w: CONTENT_WIDTH, h: 155 };
  if (fs.existsSync(COVER_LOGO_PATH)) {
    doc.image(COVER_LOGO_PATH, logoBox.x, logoBox.y, {
      fit: [logoBox.w, logoBox.h],
      align: 'center',
      valign: 'center',
    });
  } else {
    doc.fontSize(10).fillColor('#6c757d').text('COMPANY LOGO', logoBox.x, logoBox.y + 50, {
      align: 'center',
      width: logoBox.w,
    });
  }

  doc.fillColor('#1a1a2e').fontSize(24).font('Helvetica-Bold')
    .text('Fleet Energy Report', MARGIN, 228, { align: 'center', width: CONTENT_WIDTH });

  doc.fontSize(12).font('Helvetica').fillColor('#495057');
  doc.text(meta.companyName || '', MARGIN, 270, { align: 'center', width: CONTENT_WIDTH });
  doc.text(meta.periodLabel || '', MARGIN, 290, { align: 'center', width: CONTENT_WIDTH });
  doc.text(formatPeriodRange(meta.from, meta.to), MARGIN, 308, { align: 'center', width: CONTENT_WIDTH });

  doc.fontSize(10).fillColor('#6c757d');
  doc.text(`Generated: ${formatIstDateTime(meta.generatedAt)}`, MARGIN, 350, { align: 'center', width: CONTENT_WIDTH });
  doc.text(`Generated by: ${meta.generatedBy || '—'}`, MARGIN, 366, { align: 'center', width: CONTENT_WIDTH });

  // Cover description
  let y = 396;
  doc.fontSize(10).font('Helvetica-Bold').fillColor('#212529')
    .text('Report Description', MARGIN, y, { width: CONTENT_WIDTH });
  y += 14;
  doc.fontSize(8.5).font('Helvetica').fillColor('#495057')
    .text(
      'This report summarizes fleet-level energy performance, operational health, trends, alarms, and key recommendations for the selected period.',
      MARGIN,
      y,
      { width: CONTENT_WIDTH, lineGap: 2 }
    );
  y += 30;

  // Index/table of contents style table
  doc.fontSize(10).font('Helvetica-Bold').fillColor('#212529')
    .text('Report Index', MARGIN, y, { width: CONTENT_WIDTH });
  y += 12;
  const tocRows = [
    ['1', 'Executive Summary', 'Overall health score and period highlights'],
    ['2', 'Fleet Summary', 'Key KPIs: energy, power, voltage, frequency, alarms'],
    ['3', 'Energy Health Breakdown', 'Weighted factor-wise health analysis'],
    ['4', 'Fleet Charts', 'Daily consumption and trend visualizations'],
    ['5', 'Meter & Alarm Tables', 'Per-meter operational analysis and alarm details'],
    ['6', 'Rankings & Recommendations', 'Top consumers and actionable insights'],
  ];
  const tocColW = [24, 148, CONTENT_WIDTH - 24 - 148];
  doc.rect(MARGIN, y, CONTENT_WIDTH, 14).fillColor('#e9ecef').fill();
  let tx = MARGIN;
  ['#', 'Section', 'Details'].forEach((h, i) => {
    doc.fontSize(7.5).font('Helvetica-Bold').fillColor('#212529')
      .text(h, tx + 3, y + 3, { width: tocColW[i] - 6 });
    tx += tocColW[i];
  });
  y += 16;
  tocRows.forEach((row, idx) => {
    if (idx % 2 === 0) doc.rect(MARGIN, y - 1, CONTENT_WIDTH, 13).fillColor('#f8f9fa').fill();
    let x = MARGIN;
    row.forEach((cell, i) => {
      doc.fontSize(7).font('Helvetica').fillColor('#495057')
        .text(cell, x + 3, y + 2, { width: tocColW[i] - 6 });
      x += tocColW[i];
    });
    y += 13;
  });
  y += 8;

  // Meter list as table
  doc.fontSize(10).font('Helvetica-Bold').fillColor('#212529')
    .text('Meters Included In This Report', MARGIN, y, { width: CONTENT_WIDTH });
  y += 12;
  const meterRows = (payload.meters || []).map((m) => [
    m?.meterId || '—',
    m?.siteName || '—',
    m?.online ? 'Online' : 'Offline',
  ]);
  const meterColW = [CONTENT_WIDTH * 0.42, CONTENT_WIDTH * 0.36, CONTENT_WIDTH * 0.22];
  doc.rect(MARGIN, y, CONTENT_WIDTH, 14).fillColor(BRAND).fill();
  let mx = MARGIN;
  ['Device ID', 'Site', 'Status'].forEach((h, i) => {
    doc.fontSize(7.5).font('Helvetica-Bold').fillColor('#fff')
      .text(h, mx + 3, y + 3, { width: meterColW[i] - 6 });
    mx += meterColW[i];
  });
  y += 16;
  if (!meterRows.length) {
    doc.fontSize(8).font('Helvetica').fillColor('#6c757d')
      .text('No meters available for this report.', MARGIN + 3, y + 1, { width: CONTENT_WIDTH - 6 });
  } else {
    meterRows.forEach((row, idx) => {
      if (idx % 2 === 0) doc.rect(MARGIN, y - 1, CONTENT_WIDTH, 13).fillColor('#f8f9fa').fill();
      let x = MARGIN;
      row.forEach((cell, i) => {
        doc.fontSize(7).font('Helvetica').fillColor('#212529')
          .text(cell, x + 3, y + 2, { width: meterColW[i] - 6 });
        x += meterColW[i];
      });
      y += 13;
    });
  }
}

function renderExecutiveSummary(doc, payload, startY) {
  let y = sectionTitle(doc, 'Executive Summary', startY);
  const { energyHealth, executiveSummary } = payload;
  const overallTone = healthScoreTone(energyHealth.score);

  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 50, 6).fillColor('#f0f9f9').fill();
  doc.roundedRect(MARGIN, y, 4, 50, 2).fillColor(overallTone.color).fill();
  doc.fillColor(BRAND).fontSize(10).font('Helvetica-Bold')
    .text('Overall Energy Health', MARGIN + 12, y + 10);
  doc.fontSize(20).fillColor('#1a1a2e').text(`${energyHealth.score} / 100`, MARGIN + 12, y + 24);
  doc.fontSize(13).fillColor(overallTone.color).text(energyHealth.label, MARGIN + 115, y + 28);
  y += 58;

  doc.fillColor('#212529').fontSize(9.5).font('Helvetica');
  (executiveSummary.paragraphs || []).forEach((p) => {
    y = applyPage(doc, null, ensureSpace(y, doc.heightOfString(p, { width: CONTENT_WIDTH }) + 8));
    doc.text(p, MARGIN, y, { width: CONTENT_WIDTH, lineGap: 2 });
    y += doc.heightOfString(p, { width: CONTENT_WIDTH }) + 8;
  });

  return y + MINOR_GAP;
}

function healthLayoutPreset(variant = SECTION_VARIANTS.LARGE) {
  if (variant === SECTION_VARIANTS.COMPACT) {
    return {
      cardH: 52,
      cardGap: 6,
      summaryH: 46,
      summaryGap: 8,
      scoreSize: 20,
      cardScoreSize: 14,
      footerH: 16,
      showDescriptions: false,
    };
  }
  if (variant === SECTION_VARIANTS.MEDIUM) {
    return {
      cardH: 58,
      cardGap: 7,
      summaryH: 49,
      summaryGap: 9,
      scoreSize: 22,
      cardScoreSize: 15,
      footerH: 18,
      showDescriptions: true,
    };
  }
  return {
    cardH: 64,
    cardGap: 8,
    summaryH: 52,
    summaryGap: 10,
    scoreSize: 24,
    cardScoreSize: 16,
    footerH: 22,
    showDescriptions: true,
  };
}

function measureHealthSectionHeight(payload, variant = SECTION_VARIANTS.LARGE) {
  const preset = healthLayoutPreset(variant);
  const subs = payload.energyHealth?.subScores || {};
  const visibleCount = HEALTH_FACTORS.filter((factor) => subs[factor.key]).length;
  const factorRows = Math.ceil(visibleCount / 2);
  const gridH = factorRows * preset.cardH + Math.max(0, factorRows - 1) * preset.cardGap;
  return 24 + preset.summaryH + preset.summaryGap + gridH + preset.footerH + MINOR_GAP;
}

function renderFleetSummary(doc, payload, startY) {
  let y = sectionTitle(doc, 'Fleet Summary', startY);
  const s = payload.fleetSummary;
  const comp = payload.comparisons?.previousPeriod?.totalEnergyKwh;

  const kpis = [
    ['Total Energy', `${s.totalEnergyKwh ?? '—'} kWh`, comp?.deltaPct != null ? `${comp.deltaPct}% vs prev` : ''],
    ['Avg Active Power', s.avgActivePowerKw != null ? `${s.avgActivePowerKw} kW` : '—', ''],
    ['Peak Active Power', s.peakActivePowerKw != null ? `${s.peakActivePowerKw} kW` : '—', ''],
    ['Avg Voltage', s.avgVoltage != null ? `${s.avgVoltage} V` : '—', ''],
    ['Avg Power Factor', s.avgPowerFactor != null ? String(s.avgPowerFactor) : '—', ''],
    ['Avg Frequency', s.avgFrequency != null ? `${s.avgFrequency} Hz` : '—', ''],
    ['Online Meters', String(s.onlineMeters), ''],
    ['Offline Meters', String(s.offlineMeters), ''],
    ['Alarms Triggered', String(payload.alarms?.summary?.total ?? 0), ''],
    ['Critical Alarms', String(payload.alarms?.summary?.critical ?? 0), ''],
  ];

  const colW = CONTENT_WIDTH / 2;
  const rowH = 38;
  kpis.forEach((kpi, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = MARGIN + col * colW;
    const ky = y + row * rowH;
    doc.roundedRect(x, ky, colW - 6, rowH - 4, 4).strokeColor('#dee2e6').lineWidth(0.5).stroke();
    doc.fontSize(7.5).fillColor('#6c757d').font('Helvetica').text(kpi[0], x + 6, ky + 5);
    doc.fontSize(11).fillColor('#212529').font('Helvetica-Bold').text(kpi[1], x + 6, ky + 16);
    if (kpi[2]) {
      doc.fontSize(7).fillColor('#6c757d').font('Helvetica').text(kpi[2], x + 6, ky + 28);
    }
  });

  return y + Math.ceil(kpis.length / 2) * rowH + SECTION_GAP;
}

function renderHealthDetail(doc, payload, startY, variant = SECTION_VARIANTS.LARGE) {
  const preset = healthLayoutPreset(variant);
  let y = sectionTitle(doc, 'Energy Health Breakdown', startY);
  const { energyHealth } = payload;
  const subs = energyHealth?.subScores || {};
  const overallScore = Math.max(0, Math.min(100, Number(energyHealth?.score) || 0));
  const overallTone = healthScoreTone(overallScore);

  const { summaryH, summaryGap, cardGap, cardH, scoreSize, cardScoreSize, footerH, showDescriptions } = preset;
  y = applyPage(doc, null, ensureSpace(y, summaryH + 150));
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, summaryH, 6).fillColor('#f8f9fa').fill();
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, summaryH, 6).strokeColor('#dee2e6').lineWidth(0.5).stroke();
  doc.roundedRect(MARGIN, y, 4, summaryH, 2).fillColor(overallTone.color).fill();

  doc.fontSize(8.5).fillColor('#6c757d').font('Helvetica')
    .text('Composite fleet health score', MARGIN + 12, y + 8);
  doc.fontSize(scoreSize).fillColor('#1a1a2e').font('Helvetica-Bold')
    .text(String(overallScore), MARGIN + 12, y + 20);
  doc.fontSize(10).fillColor('#6c757d').font('Helvetica')
    .text('/ 100', MARGIN + (scoreSize > 22 ? 48 : 42), y + (scoreSize > 22 ? 29 : 27));
  drawHealthStatusPill(doc, MARGIN + 78, y + 22, 78, overallScore);

  const summaryBarX = MARGIN + 170;
  const summaryBarW = CONTENT_WIDTH - 182;
  doc.fontSize(7.5).fillColor('#6c757d').font('Helvetica')
    .text('Weighted score from 5 operational health indicators below', summaryBarX, y + 10, { width: summaryBarW });
  drawMiniHealthBar(doc, summaryBarX, y + 30, summaryBarW, overallScore, overallTone.color);
  doc.fontSize(7).fillColor('#6c757d')
    .text(`${energyHealth?.label || '—'} overall rating`, summaryBarX, y + 40, { width: summaryBarW });

  y += summaryH + summaryGap;

  const cardW = (CONTENT_WIDTH - cardGap) / 2;
  const visibleFactors = HEALTH_FACTORS.filter((factor) => subs[factor.key]);
  const gridRows = Math.ceil(visibleFactors.length / 2);
  const gridH = gridRows * cardH + Math.max(0, gridRows - 1) * cardGap;

  y = applyPage(doc, null, ensureSpace(y, gridH + 18));

  visibleFactors.forEach((factor, index) => {
    const sub = subs[factor.key];
    const col = index % 2;
    const row = Math.floor(index / 2);
    const cx = MARGIN + col * (cardW + cardGap);
    const cy = y + row * (cardH + cardGap);
    const score = Math.max(0, Math.min(100, Number(sub.score) || 0));
    const tone = healthScoreTone(score);
    const weightPct = Math.round((sub.weight || 0) * 100);
    const contribution = Math.round(score * (sub.weight || 0));

    doc.roundedRect(cx, cy, cardW, cardH, 5).fillColor('#ffffff').fill();
    doc.roundedRect(cx, cy, cardW, cardH, 5).strokeColor('#dee2e6').lineWidth(0.5).stroke();
    doc.roundedRect(cx, cy, 3, cardH, 1).fillColor(tone.color).fill();

    doc.fontSize(8).fillColor('#495057').font('Helvetica-Bold')
      .text(factor.label, cx + 10, cy + 6, { width: cardW - 84 });
    drawHealthStatusPill(doc, cx + cardW - 72, cy + 5, 62, score);

    doc.fontSize(cardScoreSize).fillColor('#1a1a2e').font('Helvetica-Bold')
      .text(String(score), cx + 10, cy + 22);
    doc.fontSize(7.5).fillColor('#6c757d').font('Helvetica')
      .text('/100', cx + (cardScoreSize > 14 ? 34 : 30), cy + (cardScoreSize > 14 ? 28 : 26));
    doc.fontSize(6.5).fillColor('#6c757d').font('Helvetica')
      .text(`${weightPct}% weight · +${contribution} pts`, cx + 58, cy + 26, { width: cardW - 68 });

    drawMiniHealthBar(doc, cx + 10, cy + (showDescriptions ? 40 : 36), cardW - 20, score, tone.color);

    if (showDescriptions) {
      doc.fontSize(6.5).fillColor('#6c757d').font('Helvetica')
        .text(factor.description, cx + 10, cy + 50, { width: cardW - 20 });
    }
  });

  y += gridH + 8;
  doc.fontSize(7).fillColor('#6c757d').font('Helvetica')
    .text(
      'Each factor is scored out of 100, weighted by importance, and combined into the overall energy health rating.',
      MARGIN,
      y,
      { width: CONTENT_WIDTH }
    );

  return y + footerH + MINOR_GAP;
}

function defaultChartHeight(chart, variant = SECTION_VARIANTS.LARGE) {
  if (chart.sizePresets && chart.sizePresets[variant]) return chart.sizePresets[variant];
  if (chart.preferredHeight) return chart.preferredHeight;
  if (chart.key === 'energy_by_meter') return 185;
  if (chart.key === 'daily_energy') return 210;
  return 165;
}

function chartDescriptionText(chart) {
  return (chart?.description || chart?.caption || '').trim();
}

function computeChartBlockHeight(chart, drawHeight) {
  const description = chartDescriptionText(chart);
  const insightRows = Array.isArray(chart?.insightPanel) ? chart.insightPanel.length : 0;
  const insightHeight = insightRows ? 10 + insightRows * 19 + 8 : 0;
  if (insightRows && chart?.prefersTwoColumn) {
    return Math.max(drawHeight, insightHeight + 8) + (description ? 14 : 0) + MINOR_GAP;
  }
  return drawHeight + insightHeight + (description ? 14 : 0) + MINOR_GAP;
}

function drawChartInsightPanel(doc, chart, x, y, width, height) {
  const rows = Array.isArray(chart?.insightPanel) ? chart.insightPanel : [];
  if (!rows.length) return y;

  doc.roundedRect(x, y, width, height, 6).fillColor('#f8f9fa').fill();
  doc.roundedRect(x, y, width, height, 6).strokeColor('#dee2e6').lineWidth(0.5).stroke();
  let lineY = y + 8;
  rows.forEach((row) => {
    doc.fontSize(7).font('Helvetica').fillColor('#6c757d')
      .text(row.label, x + 8, lineY, { width: width - 16 });
    lineY += 9;
    doc.fontSize(9).font('Helvetica-Bold').fillColor('#212529')
      .text(row.value || 'N/A', x + 8, lineY, { width: width - 16 });
    lineY += 10;
  });
  return lineY;
}

function renderChartsSection(doc, charts, startY, variant = SECTION_VARIANTS.LARGE) {
  if (!charts.length) return startY;

  let y = startY;
  const layoutManaged = LAYOUT_MANAGED_RENDER;
  const sectionHeading = 'Fleet Charts';
  const titleReserve = 24;

  const planned = charts.map((chart) => ({
    chart,
    height: defaultChartHeight(chart, variant),
  }));
  let totalNeeded = titleReserve + planned.reduce((sum, item) => sum + computeChartBlockHeight(item.chart, item.height), 0);

  // Keep charts readable in layout-managed mode; do not aggressively compress.
  if (layoutManaged) {
    planned.forEach((item) => {
      item.height = Math.max(item.height, item.chart?.key === 'daily_load_profile' ? 175 : 165);
    });
    totalNeeded = titleReserve + planned.reduce((sum, item) => sum + computeChartBlockHeight(item.chart, item.height), 0);
  }

  if (!layoutManaged) {
    y = applyPage(doc, null, ensureSpace(y, totalNeeded, { majorBreak: y > PAGE_TOP + 60 }));
  }
  y = sectionTitle(doc, sectionHeading, y);

  let chartIndex = 0;
  while (chartIndex < planned.length) {
    const remaining = planned.length - chartIndex;
    // In layout-managed mode, render one chart block at a time to keep spacing stable
    // and allow natural multi-page flow without overlap.
    let blockHeights = planned.slice(chartIndex, chartIndex + (layoutManaged ? 1 : Math.min(2, remaining)));
    let blockedByPageBottom = false;

    if (!layoutManaged && blockHeights.length === 2) {
      const pairHeight = blockHeights.reduce((s, b) => s + computeChartBlockHeight(b.chart, b.height), 0);
      const available = PAGE_BOTTOM - y;
      if (pairHeight > available) {
        blockHeights = [blockHeights[0]];
      } else {
        const scale = Math.min(1, available / pairHeight);
        blockHeights = blockHeights.map((b) => ({
          ...b,
          height: Math.max(110, Math.floor(b.height * scale)),
        }));
      }
    }

    for (let blockIdx = 0; blockIdx < blockHeights.length; blockIdx += 1) {
      const { chart, height } = blockHeights[blockIdx];
      const blockH = computeChartBlockHeight(chart, height);
      if (!layoutManaged && y + blockH > PAGE_BOTTOM) {
        if (maybeAddPage(doc)) y = PAGE_TOP;
      }
      if (layoutManaged && y + blockH > PAGE_BOTTOM) {
        // Start a continuation page for charts and retry this same block.
        addReportPage(doc);
        y = sectionTitle(doc, sectionHeading, PAGE_TOP);
      }
      const hasInsights = Array.isArray(chart?.insightPanel) && chart.insightPanel.length > 0;
      const canUseTwoCol = hasInsights && chart?.prefersTwoColumn && CONTENT_WIDTH >= 430;

      if (canUseTwoCol) {
        const panelGap = 10;
        const panelW = Math.min(170, Math.floor(CONTENT_WIDTH * 0.32));
        const chartW = CONTENT_WIDTH - panelW - panelGap;
        const panelH = Math.max(height, 10 + chart.insightPanel.length * 19 + 8);
        doc.image(chart.imageBuffer, MARGIN, y, { width: chartW, height });
        drawChartInsightPanel(doc, chart, MARGIN + chartW + panelGap, y, panelW, panelH);
        y += Math.max(height, panelH) + 2;
      } else {
        doc.image(chart.imageBuffer, MARGIN, y, { width: CONTENT_WIDTH, height });
        y += height + 2;
        if (hasInsights) {
          const panelHeight = 10 + chart.insightPanel.length * 19 + 8;
          drawChartInsightPanel(doc, chart, MARGIN, y, CONTENT_WIDTH, panelHeight);
          y += panelHeight + 2;
        }
      }
      const description = chartDescriptionText(chart);
      if (description) {
        doc.fontSize(7.5).fillColor('#6c757d').font('Helvetica')
          .text(`Description: ${description}`, MARGIN, y, { align: 'center', width: CONTENT_WIDTH });
        y += 12;
      }
      y += MINOR_GAP;
      chartIndex += 1;
    }

    // Guard: avoid any accidental infinite loop in pathological layout cases.
    if (layoutManaged && blockedByPageBottom && chartIndex < planned.length) {
      break;
    }
  }

  return Math.min(y + SECTION_GAP, PAGE_BOTTOM);
}

function renderRankings(doc, payload, startY) {
  const rankings = payload.rankings || {};
  const sections = [
    ['Top 5 Energy Consumers', rankings.topEnergyConsumers],
    ['Top 5 Peak Demand', rankings.topPeakDemand],
    ['Top 5 Alarm Sources', rankings.topAlarmSources],
  ].filter(([, rows]) => rows?.length);

  if (!sections.length) return startY;

  let y = startY;
  y = applyPage(doc, null, ensureSpace(y, 80, { majorBreak: y > PAGE_TOP + 100 }));
  y = sectionTitle(doc, 'Rankings', y);

  sections.forEach(([title, rows]) => {
    const blockH = 18 + rows.length * 13;
    y = applyPage(doc, null, ensureSpace(y, blockH, { minOrphanRows: 24 }));
    doc.fontSize(9.5).font('Helvetica-Bold').fillColor('#212529').text(title, MARGIN, y);
    y += 14;
    rows.forEach((row) => {
      const line = `${row.rank}. ${row.meterId} — ${row.value} ${row.unit || ''}${row.sharePct != null ? ` (${row.sharePct}%)` : ''}`;
      doc.fontSize(8.5).font('Helvetica').fillColor('#495057').text(line, MARGIN + 8, y);
      y += 13;
    });
    y += 6;
  });
  return y + MINOR_GAP;
}

function renderRecommendations(doc, payload, startY) {
  const recs = payload.recommendations || [];
  if (!recs.length) return startY;

  let y = startY;
  y = applyPage(doc, null, ensureSpace(y, 50, { minOrphanRows: 40 }));
  y = sectionTitle(doc, 'Recommendations', y);

  recs.forEach((rec) => {
    const descH = doc.heightOfString(rec.description, { width: CONTENT_WIDTH - 12 });
    y = applyPage(doc, null, ensureSpace(y, descH + 22));
    const color = rec.priority === 'high' ? '#dc3545' : rec.priority === 'medium' ? '#fd7e14' : '#6c757d';
    doc.fontSize(8.5).fillColor(color).font('Helvetica-Bold')
      .text(`[${rec.priority.toUpperCase()}] ${rec.title}`, MARGIN, y);
    y += 12;
    doc.fontSize(8.5).fillColor('#495057').font('Helvetica')
      .text(rec.description, MARGIN + 8, y, { width: CONTENT_WIDTH - 12 });
    y += descH + 8;
  });
  return y + MINOR_GAP;
}

function renderOptionalSection(doc, title, lines, startY) {
  if (!lines?.length) return startY;
  let y = startY;
  const est = 28 + lines.length * 14;
  y = applyPage(doc, null, ensureSpace(y, est, { minOrphanRows: 30 }));
  y = sectionTitle(doc, title, y);
  lines.forEach((line) => {
    y = applyPage(doc, null, ensureSpace(y, 16));
    doc.fontSize(8.5).fillColor('#495057').font('Helvetica').text(line, MARGIN, y, { width: CONTENT_WIDTH });
    y += 14;
  });
  return y + MINOR_GAP;
}

function renderMeterTable(doc, payload, startY) {
  const profiles = payload.meterProfiles?.meters || [];
  if (!profiles.length) return startY;

  let y = startY;
  y = applyPage(doc, null, ensureSpace(y, 86, { majorBreak: y > PAGE_TOP + 80 }));
  y = sectionTitle(doc, 'Individual Meter Operational Analysis', y);

  const fmt = (value, suffix = '', decimals = 2) => {
    if (value == null || !Number.isFinite(Number(value))) return '—';
    const n = Number(value);
    const out = Number.isInteger(n) ? String(n) : n.toFixed(decimals);
    return `${out}${suffix}`;
  };

  const columnConfig = [
    { id: 'label', label: payload.meterProfiles?.bucketMode === 'month' ? 'Month' : 'Date', width: 42, enabled: true, value: (r) => r.label },
    { id: 'energy', label: 'kWh', width: 38, enabled: true, value: (r) => fmt(r.energyKwh, '', 1) },
    { id: 'load', label: 'kW Min/Avg/Peak', width: 66, enabled: true, value: (r) => `${fmt(r.minPowerKw, '', 1)}/${fmt(r.avgPowerKw, '', 1)}/${fmt(r.peakPowerKw, '', 1)}` },
    { id: 'avgVoltage', label: 'Avg V', width: 36, enabled: true, value: (r) => fmt(r.avgVoltage, '', 0) },
    { id: 'voltageRange', label: 'V Min/Max', width: 45, enabled: true, value: (r) => `${fmt(r.minVoltage, '', 0)}/${fmt(r.maxVoltage, '', 0)}` },
    { id: 'avgPowerFactor', label: 'PF', width: 30, enabled: true, value: (r) => fmt(r.avgPowerFactor, '', 2) },
    { id: 'avgFrequency', label: 'Hz', width: 30, enabled: true, value: (r) => fmt(r.avgFrequency, '', 1) },
    { id: 'alarms', label: 'Alm', width: 26, enabled: true, value: (r) => String(r.alarms?.total ?? 0) },
    { id: 'health', label: 'Health', width: 34, enabled: true, value: (r) => (r.healthScore == null ? '—' : String(r.healthScore)) },
    { id: 'status', label: 'Status', width: 52, enabled: true, value: (r) => r.status || '—' },
    { id: 'avgCurrent', label: 'Avg A', width: 34, enabled: false, value: (r) => fmt(r.avgCurrent, '', 1) },
  ].filter((c) => c.enabled);

  const tableWidth = columnConfig.reduce((sum, c) => sum + c.width, 0);
  const drawMeterHeading = (meter, continued = false) => {
    doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 18, 4).fillColor(BRAND).fill();
    const status = meter.online ? 'Online' : 'Offline';
    doc.fontSize(8).font('Helvetica-Bold').fillColor('#fff')
      .text(`${meter.meterId}${continued ? ' (continued)' : ''}`, MARGIN + 8, y + 5, { width: 190 });
    doc.fontSize(7).font('Helvetica').fillColor('#fff')
      .text(`Site: ${meter.siteName || '—'}   Current Status: ${status}`, MARGIN + 205, y + 5, { width: CONTENT_WIDTH - 213 });
    y += 22;
  };

  const drawSummaryCard = (meter) => {
    const s = meter.summary || {};
    const cardH = 48;
    doc.roundedRect(MARGIN, y, CONTENT_WIDTH, cardH, 5).fillColor('#f8f9fa').fill();
    doc.roundedRect(MARGIN, y, CONTENT_WIDTH, cardH, 5).strokeColor('#dee2e6').lineWidth(0.5).stroke();
    const items = [
      ['Total Energy', fmt(s.totalEnergyKwh, ' kWh')],
      ['Overall Health', s.overallHealth != null ? `${s.overallHealth}/100` : '—'],
      ['Avg PF', fmt(s.avgPowerFactor, '', 2)],
      ['Avg Voltage', fmt(s.avgVoltage, ' V', 1)],
      ['Peak Load', fmt(s.peakPowerKw, ' kW', 1)],
      ['Total Alarms', String(s.totalAlarms ?? 0)],
      ['Coverage', s.dataCoverageLabel || '—'],
      ['Health Trend', s.healthTrend || '→ Stable'],
    ];
    const colW = CONTENT_WIDTH / 4;
    items.forEach(([label, value], idx) => {
      const col = idx % 4;
      const row = Math.floor(idx / 4);
      const x = MARGIN + col * colW;
      const ty = y + 7 + row * 21;
      doc.fontSize(6.5).font('Helvetica').fillColor('#6c757d').text(label, x + 6, ty, { width: colW - 12 });
      doc.fontSize(8).font('Helvetica-Bold').fillColor('#212529').text(value, x + 6, ty + 9, { width: colW - 12 });
    });
    y += cardH + 8;
  };

  const drawTableHeader = () => {
    let x = MARGIN;
    doc.rect(MARGIN, y, tableWidth, 14).fillColor(BRAND).fill();
    columnConfig.forEach((col) => {
      doc.fontSize(6.3).font('Helvetica-Bold').fillColor('#fff')
        .text(col.label, x + 2, y + 3, { width: col.width - 4 });
      x += col.width;
    });
    y += 15;
  };

  const drawSummaryRow = (meter) => {
    const s = meter.summary || {};
    const rowH = 15;
    doc.rect(MARGIN, y, tableWidth, rowH).fillColor('#eef2ff').fill();
    doc.fontSize(6.8).font('Helvetica-Bold').fillColor('#212529')
      .text('Summary', MARGIN + 2, y + 4, { width: 42 });
    const values = [
      fmt(s.totalEnergyKwh, '', 1),
      `—/—/${fmt(s.peakPowerKw, '', 1)}`,
      fmt(s.avgVoltage, '', 0),
      '—',
      fmt(s.avgPowerFactor, '', 2),
      '—',
      String(s.totalAlarms ?? 0),
      s.overallHealth != null ? String(s.overallHealth) : '—',
      s.dataCoveragePct != null ? `${s.dataCoveragePct}%` : '—',
    ];
    let x = MARGIN + columnConfig[0].width;
    columnConfig.slice(1).forEach((col, idx) => {
      doc.text(values[idx] || '—', x + 2, y + 4, { width: col.width - 4 });
      x += col.width;
    });
    y += rowH + 5;
  };

  const drawHighlights = (meter) => {
    const h = meter.highlights || {};
    const rows = [
      ['Best Health', h.bestHealth],
      ['Worst Health', h.worstHealth],
      ['Highest Consumption', h.highestConsumption],
      ['Highest Peak Load', h.highestPeakLoad],
      ['Most Alarms', h.mostAlarms],
      ['Longest No Data', h.longestNoData],
    ].filter(([, item]) => item);
    if (!rows.length) return;
    const blockH = 14 + Math.ceil(rows.length / 2) * 12;
    y = applyPage(doc, null, ensureSpace(y, blockH + 6));
    doc.fontSize(7.5).font('Helvetica-Bold').fillColor(BRAND).text('Performance Highlights', MARGIN, y);
    y += 12;
    const colW = CONTENT_WIDTH / 2;
    rows.forEach(([label, item], idx) => {
      const x = MARGIN + (idx % 2) * colW;
      const ty = y + Math.floor(idx / 2) * 12;
      doc.fontSize(6.8).font('Helvetica').fillColor('#495057')
        .text(`${label}: ${item.label} (${item.value})`, x, ty, { width: colW - 8 });
    });
    y += Math.ceil(rows.length / 2) * 12 + 8;
  };

  const drawDataRow = (row, idx) => {
    const rowH = 13;
    if (idx % 2 === 0) doc.rect(MARGIN, y - 1, tableWidth, rowH).fillColor('#f8f9fa').fill();
    let x = MARGIN;
    columnConfig.forEach((col) => {
      const color = col.id === 'status' && row.status === 'Critical'
        ? '#dc3545'
        : col.id === 'status' && row.status === 'Warning'
          ? '#fd7e14'
          : row.status === 'No Data'
            ? '#adb5bd'
            : '#212529';
      doc.fontSize(6.4).font(col.id === 'status' ? 'Helvetica-Bold' : 'Helvetica').fillColor(color)
        .text(col.value(row), x + 2, y + 2, { width: col.width - 4 });
      x += col.width;
    });
    y += rowH;
  };

  profiles.forEach((meter) => {
    const minStart = 22 + 48 + 8 + 14 + 3 * 13;
    y = applyPage(doc, null, ensureSpace(y, minStart, { majorBreak: false, minOrphanRows: 0 }));
    drawMeterHeading(meter);
    drawSummaryCard(meter);
    drawTableHeader();
    (meter.rows || []).forEach((row, idx) => {
      if (y + 13 > PAGE_BOTTOM) {
        y = applyPage(doc, null, ensureSpace(y, 13));
        drawMeterHeading(meter, true);
        drawTableHeader();
      }
      drawDataRow(row, idx);
    });
    y = applyPage(doc, null, ensureSpace(y, 60));
    drawSummaryRow(meter);
    drawHighlights(meter);
    y += MINOR_GAP;
  });

  return y + SECTION_GAP;
}

function renderAlarmSection(doc, payload, startY) {
  const { alarms } = payload;
  const s = alarms?.summary || {};
  const events = alarms?.events || [];

  let y = startY;
  const minStart = events.length ? 70 : 40;
  y = applyPage(doc, null, ensureSpace(y, minStart, { majorBreak: false, minOrphanRows: 50 }));
  y = sectionTitle(doc, 'Alarm Summary', y);

  doc.fontSize(8.5).font('Helvetica').fillColor('#495057');
  doc.text(
    `Total: ${s.total ?? 0}  |  Critical: ${s.critical ?? 0}  |  Warning: ${s.warning ?? 0}  |  Active: ${s.active ?? 0}  |  Acknowledged: ${s.acknowledged ?? 0}  |  Cleared: ${s.cleared ?? 0}`,
    MARGIN,
    y,
    { width: CONTENT_WIDTH }
  );
  y += 16;

  if (!events.length) {
    doc.text('No alarm events in this period.', MARGIN, y);
    return y + 16;
  }

  if (alarms.truncated) {
    doc.fontSize(7.5).fillColor('#6c757d').text(`Showing ${events.length} of ${alarms.totalEvents} events.`, MARGIN, y);
    y += 12;
  }

  const headers = ['Time', 'Device ID', 'Metric', 'Severity', 'Status'];
  const widths = [98, 88, 68, 52, 68];

  const drawAlarmHeader = () => {
    let x = MARGIN;
    doc.rect(MARGIN, y, CONTENT_WIDTH, 13).fillColor('#e9ecef').fill();
    headers.forEach((h, i) => {
      doc.fontSize(7).font('Helvetica-Bold').fillColor('#212529').text(h, x + 2, y + 2, { width: widths[i] });
      x += widths[i];
    });
    y += 15;
  };

  drawAlarmHeader();

  events.forEach((e) => {
    if (y + 12 > PAGE_BOTTOM) {
      y = applyPage(doc, null, ensureSpace(y, 12));
      drawAlarmHeader();
    }
    let x = MARGIN;
    const cells = [
      formatIstDateTime(e.triggeredAt),
      (e.meterId || '—').slice(0, 14),
      (e.metric || '').slice(0, 10),
      e.severity,
      e.status,
    ];
    doc.fontSize(7).font('Helvetica').fillColor('#495057');
    cells.forEach((cell, i) => {
      doc.text(cell, x + 2, y, { width: widths[i] });
      x += widths[i];
    });
    y += 12;
  });
  return y;
}

function scaleForVariant(height, variant) {
  if (variant === SECTION_VARIANTS.MEDIUM) return Math.max(40, Math.floor(height * 0.88));
  if (variant === SECTION_VARIANTS.COMPACT) return Math.max(32, Math.floor(height * 0.78));
  return height;
}

function fixedVariants(height) {
  return {
    [SECTION_VARIANTS.LARGE]: height,
    [SECTION_VARIANTS.MEDIUM]: height,
    [SECTION_VARIANTS.COMPACT]: height,
  };
}

function createMeasureDoc() {
  const d = new PDFDocument({ size: 'A4', margin: MARGIN, autoFirstPage: false });
  return d;
}

function buildSectionDescriptors(payload) {
  return [
    {
      id: 'executiveSummary',
      group: 'ExecutiveSummary',
      templates: ['summary'],
      measure: () => {
        const mdoc = createMeasureDoc();
        mdoc.fontSize(9.5).font('Helvetica');
        const paragraphs = payload.executiveSummary?.paragraphs || [];
        const textHeight = paragraphs.reduce(
          (s, p) => s + mdoc.heightOfString(p, { width: CONTENT_WIDTH }) + 8,
          0
        );
        const h = 24 + 58 + textHeight + MINOR_GAP;
        return {
          preferredHeight: h,
          minimumHeight: 100,
          canSplit: true,
          keepWithNext: false,
          priority: 100,
          variants: fixedVariants(h),
        };
      },
      layout: (_ctx, constraints) => ({ height: constraints.availableHeight, variant: constraints.variant }),
      render: (doc, _ctx, frame) => renderExecutiveSummary(doc, payload, frame.y),
    },
    {
      id: 'fleetSummary',
      group: 'ExecutiveSummary',
      templates: ['summary'],
      measure: () => {
        const rows = 5;
        const h = 24 + rows * 38 + SECTION_GAP;
        return {
          preferredHeight: h,
          minimumHeight: h,
          canSplit: false,
          keepWithNext: true,
          priority: 90,
          variants: fixedVariants(h),
        };
      },
      layout: (_ctx, constraints) => ({ height: constraints.availableHeight, variant: constraints.variant }),
      render: (doc, _ctx, frame) => renderFleetSummary(doc, payload, frame.y),
    },
    {
      id: 'health',
      group: 'FleetAnalytics',
      templates: ['summary', 'analytics'],
      measure: () => {
        const large = measureHealthSectionHeight(payload, SECTION_VARIANTS.LARGE);
        const medium = measureHealthSectionHeight(payload, SECTION_VARIANTS.MEDIUM);
        const compact = measureHealthSectionHeight(payload, SECTION_VARIANTS.COMPACT);
        return {
          preferredHeight: large,
          minimumHeight: compact,
          canSplit: false,
          keepWithNext: false,
          priority: 85,
          variants: {
            [SECTION_VARIANTS.LARGE]: large,
            [SECTION_VARIANTS.MEDIUM]: medium,
            [SECTION_VARIANTS.COMPACT]: compact,
          },
        };
      },
      layout: (_ctx, constraints) => ({ height: constraints.availableHeight, variant: constraints.variant }),
      render: (doc, _ctx, frame) => renderHealthDetail(doc, payload, frame.y, frame.variant),
    },
    {
      id: 'charts',
      group: 'FleetAnalytics',
      templates: ['analytics'],
      measure: () => {
        const charts = payload.charts || [];
        const large = 24 + charts.reduce((s, c) => s + defaultChartHeight(c, SECTION_VARIANTS.LARGE) + 20, 0) + SECTION_GAP;
        const medium = 24 + charts.reduce((s, c) => s + defaultChartHeight(c, SECTION_VARIANTS.MEDIUM) + 20, 0) + SECTION_GAP;
        const compact = 24 + charts.reduce((s, c) => s + defaultChartHeight(c, SECTION_VARIANTS.COMPACT) + 20, 0) + SECTION_GAP;
        return {
          preferredHeight: large,
          minimumHeight: 180,
          canSplit: true,
          keepWithNext: false,
          priority: 80,
          variants: {
            [SECTION_VARIANTS.LARGE]: large,
            [SECTION_VARIANTS.MEDIUM]: medium,
            [SECTION_VARIANTS.COMPACT]: compact,
          },
        };
      },
      layout: (_ctx, constraints) => ({ height: constraints.availableHeight, variant: constraints.variant }),
      render: (doc, _ctx, frame) => renderChartsSection(doc, payload.charts || [], frame.y, frame.variant),
    },
    {
      id: 'meterTable',
      group: 'FleetTables',
      templates: ['analytics', 'tables'],
      measure: () => {
        const profiles = payload.meterProfiles?.meters || [];
        const h = profiles.length
          ? 24 + profiles.reduce((sum, meter) => {
            const rowCount = meter.rows?.length || 0;
            const highlights = Object.values(meter.highlights || {}).filter(Boolean).length;
            const highlightsH = highlights ? 14 + Math.ceil(highlights / 2) * 12 + 8 : 0;
            return sum + 22 + 56 + 15 + rowCount * 13 + 20 + highlightsH + SECTION_GAP;
          }, 0)
          : 0;
        return {
          preferredHeight: h,
          minimumHeight: profiles.length ? 120 : 0,
          canSplit: true,
          keepWithNext: true,
          priority: 68,
          variants: fixedVariants(h),
        };
      },
      layout: (_ctx, constraints) => ({ height: constraints.availableHeight, variant: constraints.variant }),
      render: (doc, _ctx, frame) => renderMeterTable(doc, payload, frame.y),
    },
    {
      id: 'alarms',
      group: 'AlarmSummary',
      templates: ['analytics', 'tables'],
      measure: () => {
        const rows = payload.alarms?.events?.length || 0;
        const h = 24 + 16 + (rows ? 15 + rows * 12 : 20);
        return {
          preferredHeight: h,
          minimumHeight: 60,
          canSplit: true,
          keepWithNext: false,
          priority: 67,
          variants: fixedVariants(h),
        };
      },
      layout: (_ctx, constraints) => ({ height: constraints.availableHeight, variant: constraints.variant }),
      render: (doc, _ctx, frame) => renderAlarmSection(doc, payload, frame.y),
    },
    {
      id: 'rankings',
      group: 'FleetAnalytics',
      templates: ['analytics'],
      measure: () => {
        const groups = ['topEnergyConsumers', 'topPeakDemand', 'topAlarmSources']
          .map((k) => payload.rankings?.[k] || [])
          .filter((rows) => rows.length);
        const h = 24 + groups.reduce((s, rows) => s + 20 + rows.length * 13, 0) + 20;
        return {
          preferredHeight: Math.max(h, 0),
          minimumHeight: 70,
          canSplit: true,
          keepWithNext: true,
          priority: 70,
          variants: fixedVariants(h),
        };
      },
      layout: (_ctx, constraints) => ({ height: constraints.availableHeight, variant: constraints.variant }),
      render: (doc, _ctx, frame) => renderRankings(doc, payload, frame.y),
    },
    {
      id: 'recommendations',
      group: 'FleetAnalytics',
      templates: ['analytics'],
      measure: () => {
        const mdoc = createMeasureDoc();
        mdoc.fontSize(8.5).font('Helvetica');
        const recs = payload.recommendations || [];
        const recHeight = recs.reduce(
          (s, rec) => s + mdoc.heightOfString(rec.description || '', { width: CONTENT_WIDTH - 12 }) + 22,
          0
        );
        const h = recs.length ? 24 + recHeight + MINOR_GAP : 0;
        return {
          preferredHeight: h,
          minimumHeight: recs.length ? 50 : 0,
          canSplit: true,
          keepWithNext: false,
          priority: 65,
          variants: fixedVariants(h),
        };
      },
      layout: (_ctx, constraints) => ({ height: constraints.availableHeight, variant: constraints.variant }),
      render: (doc, _ctx, frame) => renderRecommendations(doc, payload, frame.y),
    },
  ].filter((section) => section.measure().preferredHeight > 0);
}

async function renderPdfReport(payload) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: MARGIN, bufferPages: true });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const debugState = { enabled: isLayoutDebugEnabled(), events: [] };

    drawPageTemplate(doc);
    renderCoverPage(doc, payload);
    const sections = buildSectionDescriptors(payload);
    const layoutContext = {
      margin: MARGIN,
      contentWidth: CONTENT_WIDTH,
      sectionGap: SECTION_GAP,
    };
    const { pages } = buildLayoutPlan({
      sections,
      context: layoutContext,
      pageTop: PAGE_TOP,
      pageBottom: PAGE_BOTTOM,
      firstTemplate: 'summary',
      debugState,
    });

    const renderablePages = pages.filter((page) => page.frames?.length);
    renderablePages.forEach((page, pageIdx) => {
      addReportPage(doc);
      let flowY = PAGE_TOP;
      page.frames.forEach((frame, frameIndex) => {
        const section = sections.find((s) => s.id === frame.sectionId);
        if (!section) return;
        if (flowY > PAGE_BOTTOM - 48) {
          addReportPage(doc);
          flowY = PAGE_TOP;
        }
        const flowFrame = { ...frame, y: flowY };
        let endY;
        LAYOUT_MANAGED_RENDER = true;
        try {
          endY = section.render(doc, layoutContext, flowFrame);
        } finally {
          LAYOUT_MANAGED_RENDER = false;
        }
        const actualEnd = Number.isFinite(endY) ? endY : flowFrame.y + frame.height;
        if (actualEnd > PAGE_BOTTOM) {
          flowY = PAGE_TOP;
          if (frameIndex < page.frames.length - 1) {
            addReportPage(doc);
          }
        } else {
          flowY = actualEnd + SECTION_GAP;
        }
        if (debugState.enabled) {
          drawDebugOverlay(doc, flowFrame, PAGE_BOTTOM - flowY);
        }
      });
      if (debugState.enabled) {
        doc.fontSize(6.5).fillColor('#6c757d').text(
          `Template: ${page.template} · pageIndex=${pageIdx} · debug=true`,
          MARGIN,
          PAGE_TOP - 14
        );
      }
    });

    // Footer stamping is temporarily disabled because PDFKit can auto-paginate
    // if footer text is written outside the writable bottom margin, which can
    // create cascading blank pages.

    doc.end();
  });
}

module.exports = { renderPdfReport };
