const PDFDocument = require('pdfkit');

const BRAND = '#4db3b3';
const MARGIN = 50;
const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const FOOTER_RESERVED = 58;
const PAGE_BOTTOM = PAGE_HEIGHT - FOOTER_RESERVED;
const PAGE_TOP = MARGIN;
const SECTION_GAP = 10;
const MINOR_GAP = 6;

const HEALTH_FACTORS = [
  {
    key: 'powerFactor',
    label: 'Power Factor',
    description: 'How efficiently the fleet uses electrical power',
  },
  {
    key: 'voltageStability',
    label: 'Voltage Stability',
    description: 'How stable supply voltage stayed during the period',
  },
  {
    key: 'alarmFrequency',
    label: 'Alarm Frequency',
    description: 'How often alarms were triggered across the fleet',
  },
  {
    key: 'meterAvailability',
    label: 'Meter Availability',
    description: 'Share of meters communicating at report generation',
  },
  {
    key: 'offlineDuration',
    label: 'Communication Uptime',
    description: 'How long offline meters stayed disconnected',
  },
];

function healthScoreTone(score) {
  const value = Math.max(0, Math.min(100, Number(score) || 0));
  if (value >= 90) return { label: 'Excellent', color: '#198754', tint: '#d1e7dd' };
  if (value >= 75) return { label: 'Good', color: '#0d6efd', tint: '#cfe2ff' };
  if (value >= 60) return { label: 'Fair', color: '#fd7e14', tint: '#fff3cd' };
  return { label: 'Needs attention', color: '#dc3545', tint: '#f8d7da' };
}

function drawHealthStatusPill(doc, x, y, width, score) {
  const tone = healthScoreTone(score);
  doc.roundedRect(x, y, width, 14, 7).fillColor(tone.tint).fill();
  doc.fontSize(6.5).fillColor(tone.color).font('Helvetica-Bold')
    .text(tone.label, x, y + 3.5, { width, align: 'center' });
  return tone;
}

function drawMiniHealthBar(doc, x, y, width, score, color) {
  const value = Math.max(0, Math.min(100, Number(score) || 0));
  doc.roundedRect(x, y, width, 6, 3).fillColor('#e9ecef').fill();
  if (value > 0) {
    doc.roundedRect(x, y, Math.max(4, (value / 100) * width), 6, 3).fillColor(color).fill();
  }
}

function formatIstDateTime(date) {
  return new Date(date).toLocaleString('en-IN', {
    timeZone: 'Asia/Kolkata',
    dateStyle: 'medium',
    timeStyle: 'short',
  });
}

function formatPeriodRange(from, to) {
  const opts = { timeZone: 'Asia/Kolkata', dateStyle: 'medium' };
  return `${new Date(from).toLocaleDateString('en-IN', opts)} — ${new Date(to).toLocaleDateString('en-IN', opts)}`;
}

function addPageFooter(doc, pageNum, totalPages, generatedAt) {
  const y = PAGE_HEIGHT - 42;
  doc.fontSize(7.5).fillColor('#6c757d');
  doc.text(
    `Generated by Energy Dashboard · ${formatIstDateTime(generatedAt)} · Page ${pageNum} of ${totalPages}`,
    MARGIN,
    y,
    { align: 'center', width: CONTENT_WIDTH }
  );
  doc.text(
    'Prepared By: _______________    Verified By: _______________    Approved By: _______________',
    MARGIN,
    y + 11,
    { align: 'center', width: CONTENT_WIDTH }
  );
}

function sectionTitle(doc, title, y) {
  doc.fillColor(BRAND).fontSize(13).font('Helvetica-Bold').text(title, MARGIN, y);
  doc.moveTo(MARGIN, y + 16).lineTo(PAGE_WIDTH - MARGIN, y + 16).strokeColor(BRAND).lineWidth(0.75).stroke();
  return y + 24;
}

function ensureSpace(y, needed, { majorBreak = false, minOrphanRows = 0 } = {}) {
  const required = needed + minOrphanRows;
  if (majorBreak && y > PAGE_TOP + 40) {
    return { y: PAGE_TOP, newPage: true };
  }
  if (y + required > PAGE_BOTTOM) {
    return { y: PAGE_TOP, newPage: true };
  }
  return { y, newPage: false };
}

function applyPage(doc, state, result) {
  if (result.newPage) doc.addPage();
  return result.y;
}

function renderCoverPage(doc, payload) {
  const { meta } = payload;
  doc.rect(MARGIN, 80, CONTENT_WIDTH, 60).strokeColor('#dee2e6').lineWidth(1).stroke();
  doc.fontSize(10).fillColor('#6c757d').text('COMPANY LOGO', MARGIN, 100, { align: 'center', width: CONTENT_WIDTH });

  doc.fillColor('#1a1a2e').fontSize(24).font('Helvetica-Bold')
    .text('Fleet Energy Report', MARGIN, 180, { align: 'center', width: CONTENT_WIDTH });

  doc.fontSize(12).font('Helvetica').fillColor('#495057');
  doc.text(meta.companyName || '', MARGIN, 220, { align: 'center', width: CONTENT_WIDTH });
  doc.text(meta.periodLabel || '', MARGIN, 240, { align: 'center', width: CONTENT_WIDTH });
  doc.text(formatPeriodRange(meta.from, meta.to), MARGIN, 258, { align: 'center', width: CONTENT_WIDTH });

  doc.fontSize(10).fillColor('#6c757d');
  doc.text(`Generated: ${formatIstDateTime(meta.generatedAt)}`, MARGIN, 300, { align: 'center', width: CONTENT_WIDTH });
  doc.text(`Generated by: ${meta.generatedBy || '—'}`, MARGIN, 316, { align: 'center', width: CONTENT_WIDTH });
}

function renderExecutiveSummary(doc, payload, startY) {
  let y = sectionTitle(doc, 'Executive Summary', startY);
  const { energyHealth, executiveSummary } = payload;
  const overallTone = healthScoreTone(energyHealth.score);

  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 50, 6).fillColor('#f0f9f9').fill();
  doc.roundedRect(MARGIN, y, 4, 50, 2).fillColor(overallTone.color).fill();
  doc.fillColor(BRAND).fontSize(10).font('Helvetica-Bold')
    .text('Overall Energy Health', MARGIN + 12, y + 10);
  doc.fontSize(20).fillColor('#1a1a2e').text(`${energyHealth.score} / 100`, MARGIN + 12, y + 24);
  doc.fontSize(13).fillColor(overallTone.color).text(energyHealth.label, MARGIN + 115, y + 28);
  y += 58;

  doc.fillColor('#212529').fontSize(9.5).font('Helvetica');
  (executiveSummary.paragraphs || []).forEach((p) => {
    y = applyPage(doc, null, ensureSpace(y, doc.heightOfString(p, { width: CONTENT_WIDTH }) + 8));
    doc.text(p, MARGIN, y, { width: CONTENT_WIDTH, lineGap: 2 });
    y += doc.heightOfString(p, { width: CONTENT_WIDTH }) + 8;
  });

  return y + MINOR_GAP;
}

function renderFleetSummary(doc, payload, startY) {
  let y = sectionTitle(doc, 'Fleet Summary', startY);
  const s = payload.fleetSummary;
  const comp = payload.comparisons?.previousPeriod?.totalEnergyKwh;

  const kpis = [
    ['Total Energy', `${s.totalEnergyKwh ?? '—'} kWh`, comp?.deltaPct != null ? `${comp.deltaPct}% vs prev` : ''],
    ['Avg Active Power', s.avgActivePowerKw != null ? `${s.avgActivePowerKw} kW` : '—', ''],
    ['Peak Active Power', s.peakActivePowerKw != null ? `${s.peakActivePowerKw} kW` : '—', ''],
    ['Avg Voltage', s.avgVoltage != null ? `${s.avgVoltage} V` : '—', ''],
    ['Avg Power Factor', s.avgPowerFactor != null ? String(s.avgPowerFactor) : '—', ''],
    ['Avg Frequency', s.avgFrequency != null ? `${s.avgFrequency} Hz` : '—', ''],
    ['Online Meters', String(s.onlineMeters), ''],
    ['Offline Meters', String(s.offlineMeters), ''],
    ['Alarms Triggered', String(payload.alarms?.summary?.total ?? 0), ''],
    ['Critical Alarms', String(payload.alarms?.summary?.critical ?? 0), ''],
  ];

  const colW = CONTENT_WIDTH / 2;
  const rowH = 38;
  kpis.forEach((kpi, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = MARGIN + col * colW;
    const ky = y + row * rowH;
    doc.roundedRect(x, ky, colW - 6, rowH - 4, 4).strokeColor('#dee2e6').lineWidth(0.5).stroke();
    doc.fontSize(7.5).fillColor('#6c757d').font('Helvetica').text(kpi[0], x + 6, ky + 5);
    doc.fontSize(11).fillColor('#212529').font('Helvetica-Bold').text(kpi[1], x + 6, ky + 16);
    if (kpi[2]) {
      doc.fontSize(7).fillColor('#6c757d').font('Helvetica').text(kpi[2], x + 6, ky + 28);
    }
  });

  return y + Math.ceil(kpis.length / 2) * rowH + SECTION_GAP;
}

function renderHealthDetail(doc, payload, startY) {
  let y = sectionTitle(doc, 'Energy Health Breakdown', startY);
  const { energyHealth } = payload;
  const subs = energyHealth?.subScores || {};
  const overallScore = Math.max(0, Math.min(100, Number(energyHealth?.score) || 0));
  const overallTone = healthScoreTone(overallScore);

  const summaryH = 52;
  y = applyPage(doc, null, ensureSpace(y, summaryH + 150));
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, summaryH, 6).fillColor('#f8f9fa').fill();
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, summaryH, 6).strokeColor('#dee2e6').lineWidth(0.5).stroke();
  doc.roundedRect(MARGIN, y, 4, summaryH, 2).fillColor(overallTone.color).fill();

  doc.fontSize(8.5).fillColor('#6c757d').font('Helvetica')
    .text('Composite fleet health score', MARGIN + 12, y + 8);
  doc.fontSize(24).fillColor('#1a1a2e').font('Helvetica-Bold')
    .text(String(overallScore), MARGIN + 12, y + 20);
  doc.fontSize(10).fillColor('#6c757d').font('Helvetica')
    .text('/ 100', MARGIN + 48, y + 29);
  drawHealthStatusPill(doc, MARGIN + 78, y + 24, 78, overallScore);

  const summaryBarX = MARGIN + 170;
  const summaryBarW = CONTENT_WIDTH - 182;
  doc.fontSize(7.5).fillColor('#6c757d').font('Helvetica')
    .text('Weighted score from 5 operational health indicators below', summaryBarX, y + 10, { width: summaryBarW });
  drawMiniHealthBar(doc, summaryBarX, y + 30, summaryBarW, overallScore, overallTone.color);
  doc.fontSize(7).fillColor('#6c757d')
    .text(`${energyHealth?.label || '—'} overall rating`, summaryBarX, y + 40, { width: summaryBarW });

  y += summaryH + 10;

  const cardGap = 8;
  const cardW = (CONTENT_WIDTH - cardGap) / 2;
  const cardH = 64;
  const visibleFactors = HEALTH_FACTORS.filter((factor) => subs[factor.key]);
  const gridRows = Math.ceil(visibleFactors.length / 2);
  const gridH = gridRows * cardH + Math.max(0, gridRows - 1) * cardGap;

  y = applyPage(doc, null, ensureSpace(y, gridH + 18));

  visibleFactors.forEach((factor, index) => {
    const sub = subs[factor.key];
    const col = index % 2;
    const row = Math.floor(index / 2);
    const cx = MARGIN + col * (cardW + cardGap);
    const cy = y + row * (cardH + cardGap);
    const score = Math.max(0, Math.min(100, Number(sub.score) || 0));
    const tone = healthScoreTone(score);
    const weightPct = Math.round((sub.weight || 0) * 100);
    const contribution = Math.round(score * (sub.weight || 0));

    doc.roundedRect(cx, cy, cardW, cardH, 5).fillColor('#ffffff').fill();
    doc.roundedRect(cx, cy, cardW, cardH, 5).strokeColor('#dee2e6').lineWidth(0.5).stroke();
    doc.roundedRect(cx, cy, 3, cardH, 1).fillColor(tone.color).fill();

    doc.fontSize(8).fillColor('#495057').font('Helvetica-Bold')
      .text(factor.label, cx + 10, cy + 7, { width: cardW - 84 });
    drawHealthStatusPill(doc, cx + cardW - 72, cy + 6, 62, score);

    doc.fontSize(16).fillColor('#1a1a2e').font('Helvetica-Bold')
      .text(String(score), cx + 10, cy + 24);
    doc.fontSize(7.5).fillColor('#6c757d').font('Helvetica')
      .text('/100', cx + 34, cy + 30);
    doc.fontSize(6.5).fillColor('#6c757d').font('Helvetica')
      .text(`${weightPct}% weight · +${contribution} pts`, cx + 58, cy + 30, { width: cardW - 68 });

    drawMiniHealthBar(doc, cx + 10, cy + 42, cardW - 20, score, tone.color);

    doc.fontSize(6.5).fillColor('#6c757d').font('Helvetica')
      .text(factor.description, cx + 10, cy + 52, { width: cardW - 20 });
  });

  y += gridH + 8;
  doc.fontSize(7).fillColor('#6c757d').font('Helvetica')
    .text(
      'Each factor is scored out of 100, weighted by importance, and combined into the overall energy health rating.',
      MARGIN,
      y,
      { width: CONTENT_WIDTH }
    );

  return y + 14 + MINOR_GAP;
}

function defaultChartHeight(chart) {
  if (chart.preferredHeight) return chart.preferredHeight;
  if (chart.key === 'energy_by_meter') return 185;
  if (chart.key === 'daily_energy') return 210;
  return 165;
}

function computeChartBlockHeight(chart, drawHeight) {
  return drawHeight + (chart.caption ? 14 : 0) + MINOR_GAP;
}

function renderChartsSection(doc, charts, startY) {
  if (!charts.length) return startY;

  let y = startY;
  let sectionStarted = false;
  let chartIndex = 0;

  while (chartIndex < charts.length) {
    const remaining = charts.length - chartIndex;
    let blockHeights = [];
    let totalBlock = 24;

    for (let i = 0; i < Math.min(2, remaining); i += 1) {
      const chart = charts[chartIndex + i];
      const h = defaultChartHeight(chart);
      blockHeights.push({ chart, height: h });
      totalBlock += computeChartBlockHeight(chart, h);
    }

    if (!sectionStarted) {
      y = applyPage(doc, null, ensureSpace(y, totalBlock, { majorBreak: y > PAGE_TOP + 60 }));
      y = sectionTitle(doc, 'Fleet Charts', y);
      sectionStarted = true;
    } else if (y + totalBlock > PAGE_BOTTOM) {
      doc.addPage();
      y = PAGE_TOP;
    }

    if (blockHeights.length === 2 && y + totalBlock > PAGE_BOTTOM) {
      blockHeights = [blockHeights[0]];
      totalBlock = 24 + computeChartBlockHeight(blockHeights[0].chart, blockHeights[0].height);
    }

    const pairHeight = blockHeights.reduce((s, b) => s + computeChartBlockHeight(b.chart, b.height), 0);
    if (blockHeights.length === 2) {
      const available = PAGE_BOTTOM - y - 24;
      const scale = Math.min(1, available / pairHeight);
      blockHeights = blockHeights.map((b) => ({
        ...b,
        height: Math.max(130, Math.floor(b.height * scale)),
      }));
    }

    blockHeights.forEach(({ chart, height }) => {
      const blockH = computeChartBlockHeight(chart, height);
      if (y + blockH > PAGE_BOTTOM) {
        doc.addPage();
        y = PAGE_TOP;
      }
      doc.image(chart.imageBuffer, MARGIN, y, { width: CONTENT_WIDTH, height });
      y += height + 2;
      if (chart.caption) {
        doc.fontSize(7.5).fillColor('#6c757d').font('Helvetica')
          .text(chart.caption, MARGIN, y, { align: 'center', width: CONTENT_WIDTH });
        y += 12;
      }
      y += MINOR_GAP;
      chartIndex += 1;
    });
  }

  return y + SECTION_GAP;
}

function renderRankings(doc, payload, startY) {
  const rankings = payload.rankings || {};
  const sections = [
    ['Top 5 Energy Consumers', rankings.topEnergyConsumers],
    ['Top 5 Peak Demand', rankings.topPeakDemand],
    ['Top 5 Alarm Sources', rankings.topAlarmSources],
  ].filter(([, rows]) => rows?.length);

  if (!sections.length) return startY;

  let y = startY;
  y = applyPage(doc, null, ensureSpace(y, 80, { majorBreak: y > PAGE_TOP + 100 }));
  y = sectionTitle(doc, 'Rankings', y);

  sections.forEach(([title, rows]) => {
    const blockH = 18 + rows.length * 13;
    y = applyPage(doc, null, ensureSpace(y, blockH, { minOrphanRows: 24 }));
    doc.fontSize(9.5).font('Helvetica-Bold').fillColor('#212529').text(title, MARGIN, y);
    y += 14;
    rows.forEach((row) => {
      const line = `${row.rank}. ${row.meterId} — ${row.value} ${row.unit || ''}${row.sharePct != null ? ` (${row.sharePct}%)` : ''}`;
      doc.fontSize(8.5).font('Helvetica').fillColor('#495057').text(line, MARGIN + 8, y);
      y += 13;
    });
    y += 6;
  });
  return y + MINOR_GAP;
}

function renderRecommendations(doc, payload, startY) {
  const recs = payload.recommendations || [];
  if (!recs.length) return startY;

  let y = startY;
  y = applyPage(doc, null, ensureSpace(y, 50, { minOrphanRows: 40 }));
  y = sectionTitle(doc, 'Recommendations', y);

  recs.forEach((rec) => {
    const descH = doc.heightOfString(rec.description, { width: CONTENT_WIDTH - 12 });
    y = applyPage(doc, null, ensureSpace(y, descH + 22));
    const color = rec.priority === 'high' ? '#dc3545' : rec.priority === 'medium' ? '#fd7e14' : '#6c757d';
    doc.fontSize(8.5).fillColor(color).font('Helvetica-Bold')
      .text(`[${rec.priority.toUpperCase()}] ${rec.title}`, MARGIN, y);
    y += 12;
    doc.fontSize(8.5).fillColor('#495057').font('Helvetica')
      .text(rec.description, MARGIN + 8, y, { width: CONTENT_WIDTH - 12 });
    y += descH + 8;
  });
  return y + MINOR_GAP;
}

function renderOptionalSection(doc, title, lines, startY) {
  if (!lines?.length) return startY;
  let y = startY;
  const est = 28 + lines.length * 14;
  y = applyPage(doc, null, ensureSpace(y, est, { minOrphanRows: 30 }));
  y = sectionTitle(doc, title, y);
  lines.forEach((line) => {
    y = applyPage(doc, null, ensureSpace(y, 16));
    doc.fontSize(8.5).fillColor('#495057').font('Helvetica').text(line, MARGIN, y, { width: CONTENT_WIDTH });
    y += 14;
  });
  return y + MINOR_GAP;
}

function renderMeterTable(doc, payload, startY) {
  const meters = payload.meters || [];
  if (!meters.length) return startY;

  let y = startY;
  y = applyPage(doc, null, ensureSpace(y, 60, { majorBreak: y > PAGE_TOP + 80 }));
  y = sectionTitle(doc, 'Individual Meter Summary', y);

  const headers = ['Device ID', 'Site', 'kWh', 'Peak kW', 'Avg V', 'Avg PF', 'Alarms', 'Status'];
  const colWidths = [88, 68, 48, 44, 38, 38, 36, 42];

  const drawHeader = () => {
    let x = MARGIN;
    doc.rect(MARGIN, y, CONTENT_WIDTH, 14).fillColor(BRAND).fill();
    headers.forEach((h, i) => {
      doc.fontSize(7).font('Helvetica-Bold').fillColor('#fff').text(h, x + 3, y + 3, { width: colWidths[i] - 4 });
      x += colWidths[i];
    });
    y += 16;
  };

  drawHeader();

  meters.forEach((m, idx) => {
    if (y + 14 > PAGE_BOTTOM) {
      doc.addPage();
      y = PAGE_TOP;
      drawHeader();
    }
    if (idx % 2 === 0) {
      doc.rect(MARGIN, y - 1, CONTENT_WIDTH, 13).fillColor('#f8f9fa').fill();
    }
    let x = MARGIN;
    const cells = [
      (m.meterId || '—').slice(0, 16),
      (m.siteName || '').slice(0, 11),
      String(m.totalEnergyKwh ?? '—'),
      m.peakPowerKw != null ? String(m.peakPowerKw) : '—',
      m.avgVoltage != null ? String(m.avgVoltage) : '—',
      m.avgPowerFactor != null ? String(m.avgPowerFactor) : '—',
      String(m.alarmCount ?? 0),
      m.online ? 'Online' : 'Offline',
    ];
    doc.fontSize(7).font('Helvetica').fillColor('#212529');
    cells.forEach((cell, i) => {
      doc.text(cell, x + 2, y, { width: colWidths[i] - 4 });
      x += colWidths[i];
    });
    y += 13;
  });
  return y + SECTION_GAP;
}

function renderAlarmSection(doc, payload, startY) {
  const { alarms } = payload;
  const s = alarms?.summary || {};
  const events = alarms?.events || [];

  let y = startY;
  const minStart = events.length ? 70 : 40;
  y = applyPage(doc, null, ensureSpace(y, minStart, { majorBreak: false, minOrphanRows: 50 }));
  y = sectionTitle(doc, 'Alarm Summary', y);

  doc.fontSize(8.5).font('Helvetica').fillColor('#495057');
  doc.text(
    `Total: ${s.total ?? 0}  |  Critical: ${s.critical ?? 0}  |  Warning: ${s.warning ?? 0}  |  Active: ${s.active ?? 0}  |  Acknowledged: ${s.acknowledged ?? 0}  |  Cleared: ${s.cleared ?? 0}`,
    MARGIN,
    y,
    { width: CONTENT_WIDTH }
  );
  y += 16;

  if (!events.length) {
    doc.text('No alarm events in this period.', MARGIN, y);
    return y + 16;
  }

  if (alarms.truncated) {
    doc.fontSize(7.5).fillColor('#6c757d').text(`Showing ${events.length} of ${alarms.totalEvents} events.`, MARGIN, y);
    y += 12;
  }

  const headers = ['Time', 'Device ID', 'Metric', 'Severity', 'Status'];
  const widths = [98, 88, 68, 52, 68];

  const drawAlarmHeader = () => {
    let x = MARGIN;
    doc.rect(MARGIN, y, CONTENT_WIDTH, 13).fillColor('#e9ecef').fill();
    headers.forEach((h, i) => {
      doc.fontSize(7).font('Helvetica-Bold').fillColor('#212529').text(h, x + 2, y + 2, { width: widths[i] });
      x += widths[i];
    });
    y += 15;
  };

  drawAlarmHeader();

  events.forEach((e) => {
    if (y + 12 > PAGE_BOTTOM) {
      doc.addPage();
      y = PAGE_TOP;
      drawAlarmHeader();
    }
    let x = MARGIN;
    const cells = [
      formatIstDateTime(e.triggeredAt),
      (e.meterId || '—').slice(0, 14),
      (e.metric || '').slice(0, 10),
      e.severity,
      e.status,
    ];
    doc.fontSize(7).font('Helvetica').fillColor('#495057');
    cells.forEach((cell, i) => {
      doc.text(cell, x + 2, y, { width: widths[i] });
      x += widths[i];
    });
    y += 12;
  });
  return y;
}

async function renderPdfReport(payload) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: MARGIN, bufferPages: true });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    renderCoverPage(doc, payload);
    doc.addPage();

    let y = PAGE_TOP;
    y = renderExecutiveSummary(doc, payload, y);
    y = renderFleetSummary(doc, payload, y);
    y = renderHealthDetail(doc, payload, y);

    y = renderChartsSection(doc, payload.charts || [], y + SECTION_GAP);

    y = renderRankings(doc, payload, y);
    y = renderRecommendations(doc, payload, y);

    if (payload.sustainability?.visible) {
      y = renderOptionalSection(doc, 'Sustainability', [
        `Estimated CO₂: ${payload.sustainability.estimatedCo2Tonnes} tonnes (${payload.sustainability.estimatedCo2Kg} kg)`,
        `Emission factor: ${payload.sustainability.emissionFactorKgCo2PerKwh} kg CO₂/kWh`,
        payload.sustainability.esgNote,
      ].filter(Boolean), y);
    }

    if (payload.cost?.visible) {
      y = renderOptionalSection(doc, 'Estimated Energy Cost', [
        `Total energy: ${payload.cost.totalEnergyKwh} kWh`,
        `Rate: ${payload.cost.currency} ${payload.cost.ratePerKwh}/kWh`,
        `Estimated cost: ${payload.cost.currency} ${payload.cost.estimatedCost.toLocaleString('en-IN')}`,
      ], y);
    }

    y = renderMeterTable(doc, payload, y);
    renderAlarmSection(doc, payload, y);

    const range = doc.bufferedPageRange();
    const totalPages = range.count;
    for (let i = range.start; i < range.start + totalPages; i += 1) {
      doc.switchToPage(i);
      addPageFooter(doc, i - range.start + 1, totalPages, payload.meta.generatedAt);
    }

    doc.end();
  });
}

module.exports = { renderPdfReport };
