name: Build and Deploy Fullstack App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Make sure npm installs devDependencies during the workflow build
    env:
      NPM_CONFIG_PRODUCTION: "false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install backend dependencies (clean)
        run: npm ci

      - name: Install frontend dev dependencies & build
        working-directory: frontend
        run: |
          # install exactly what's in package-lock, including dev deps (vite, etc.)
          npm ci --include=dev
          npm run build
        # when this step finishes the built frontend should be in frontend/dist (or your configured output)

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Gsn-Iot-Dashboard
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
