name: Build and Deploy Fullstack App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # ensure devDependencies are installed during this workflow
      NPM_CONFIG_PRODUCTION: "false"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend dependencies (root)
        run: npm ci

      - name: Build frontend (install dev deps & build)
        working-directory: ./frontend
        run: |
          npm ci --include=dev
          npm run build

      - name: Remove frontend node_modules to reduce package size
        run: |
          rm -rf frontend/node_modules || true

      # Optional: create a small listing so you can confirm dist exists in logs
      - name: List built frontend
        run: |
          echo "Frontend dist contents:"
          ls -la frontend/dist || true

      - name: Deploy to Azure Web App (ZIP deploy)
        uses: azure/webapps-deploy@v2
        with:
          app-name: Gsn-Iot-Dashboard
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
